# Algorithm parameters
[algorithm_params]
time_limit = 3600.0
gap_tolerance = 1e-5
solver = "CPLEX"
verbose = true


# Solver specific parameters
[solver_params.master]
solver = "CPLEX"

[solver_params.sub]
solver = "CPLEX"
# CPX_PARAM_LPMETHOD = "CPX_ALG_DUAL"

[solver_params.dcglp]
solver = "CPLEX"


# Cut strategy configuration
[cut_strategy]
type = "DISJUNCTIVE_CUT"
base_cut_strategy = "KNAPSACK_CUT"
# base_cut_strategy = "CLASSICAL_CUT"
norm_type = "L1NORM"
# cut_strengthening = "PURE_DISJUNCTION"
cut_strengthening = "STRENGTHENED_DISJUNCTION"
use_two_sided_cuts = true
include_master_cuts = true
reuse_dcglp = false
verbose = true

