# Algorithm parameters
[algorithm_params]
time_limit = 3600.0
gap_tolerance = 1e-9
solver = "CPLEX"
# solver = "Gurobi"
verbose = true


# Solver specific parameters
[solver_params.master]
solver = "CPLEX"
# solver = "Gurobi"
# CPX_PARAM_EPINT = 0.0
# CPX_PARAM_EPGAP = 1e-9
# CPX_PARAM_EPRHS = 1e-9

[solver_params.sub]
solver = "CPLEX"
# solver = "Gurobi"

[solver_params.dcglp]
solver = "CPLEX"
# solver = "Gurobi"


# Cut strategy configuration
[cut_strategy]
type = "DISJUNCTIVE_CUT"
base_cut_strategy = "FAT_KNAPSACK_CUT"
norm_type = "L1NORM"
# cut_strengthening = "PURE_DISJUNCTION"
cut_strengthening = "STRENGTHENED_DISJUNCTION"
use_two_sided_cuts = true
include_master_cuts = true
reuse_dcglp = true
verbose = true

# now we use linear relaxation UB for the master problem
# params.time_limit = 600