# Algorithm parameters
[algorithm_params]
time_limit = 1000.0
gap_tolerance = 1e-3
solver = "Gurobi"
verbose = true


# Solver specific parameters
[solver_params.master]
solver = "Gurobi"

[solver_params.sub]
solver = "Gurobi"
# CPX_PARAM_LPMETHOD = "CPX_ALG_PRIMAL"

[solver_params.dcglp]
solver = "Gurobi"


# Cut strategy configuration
[cut_strategy]
type = "DISJUNCTIVE_CUT"
base_cut_strategy = "KNAPSACK_CUT"
norm_type = "L1NORM"
cut_strengthening = "PURE_DISJUNCTION"
use_two_sided_cuts = true
include_master_cuts = true
reuse_dcglp = false
verbose = true

# now we use linear relaxation UB for the master problem
# params.time_limit = 600