# Algorithm parameters
[algorithm_params]
time_limit = 13400.0
gap_tolerance = 1e-3
solver = "CPLEX"
verbose = true


# Solver specific parameters
[solver_params.master]
solver = "CPLEX"

[solver_params.sub]
solver = "CPLEX"

[solver_params.dcglp]
solver = "CPLEX"


# Cut strategy configuration
[cut_strategy]
type = "DISJUNCTIVE_CUT"
base_cut_strategy = "FAT_KNAPSACK_CUT"
norm_type = "LINFNORM"
cut_strengthening = "PURE_DISJUNCTION"
use_two_sided_cuts = true
include_master_cuts = true
reuse_dcglp = true
verbose = true

# now we use linear relaxation UB for the master problem
# params.time_limit = 600